version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.19
      - image: postgres:12
        environment:
          POSTGRES_PASSWORD: citest
    environment:
      TEST_RESULTS: /tmp/test-results
      GO111MODULE: 'on'
    steps:
      - checkout

      - run: git describe HEAD

      - type: setup_remote_docker
        reusable: true

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - v1-pkg-cache

      - run:
          name: Install tools
          environment:
            GO111MODULE: 'off'
          command: |
            go get golang.org/x/lint/golint
            go get github.com/jstemmer/go-junit-report

      - run:
          name: Install dependencies
          command: |
            # Install source dependencies.
            go mod tidy -v

      - run:
          name: Ensure dependency specification is up to date.
          # "go mod tidy" should not cause updates to the config.
          command: git diff --name-only --exit-code

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - /go/pkg

      - run:
          name: Install Go packages
          command: go install -v ./...

      - run:
          name: Build docker image
          command: |
            make docker BUILD="$CIRCLE_BUILD_NUM"
            docker images

      - run:
          name: Run linters
          # TODO: Switch golint to ./... - https://github.com/golang/lint/issues/320
          command: |
            go list ./... | grep -v /vendor/ | xargs -L1 golint
            go vet -x ./...

      - run:
          name: Run basic tests
          command: |
            mkdir -p "${TEST_RESULTS}"
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
          environment:
            PGHOST: 127.0.0.1
            PGUSER: postgres
            PGSSLMODE: disable
            PGPASSWORD: citest

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^[0-9]+[.][0-9]+[.][0-9]+.*/
